### ISSUE TITLE
Empty output file.

### ISSUE THREAD

**Issue by salvationFPS** [unispeech/swig-wrapper#1]
Hello, im using java wrapper for unimrcp and example UniSynth.java
When im trying to synth speech with mrcpv1 im getting file filled by zero bytes.
When im trying to synth speech with mrcpv2 im getting empty file.

Im capturing packets with wireshark and i can see that server responds with rtp packets that contains audio data, but client cant write data to file.

Im running this code from intellij idea, output file path in my home directory, there is no proplems like permission denied etc.
Using debug shows me that there is no callings to method public boolean WriteFrame()   during client execution.

But when im running client using terminal like:
./umc -> run synth %myProfileName% result file in /usr/loca;/unimrcp/var/synth-8k-*.pcm contains valid output audio.

Im so bad at JNI, so can anyone explain me, whats the problem? Thanks.

**Comment by achaloyan** [comment]
Sorry, but not sure if there is anyone out here currently available to support you with the swig-wrapper issues.

**Comment by psalajka** [comment]
Hello, my name is Petr Salajka. I was a colleague of original swig-wrapper maintainer Tomas Valenta. Unfortunately, he died more than two years ago. It looks like, I should continue his work because we still need the wrapper here at the University of West Bohemia. I still feel a little overwhelmed, trying to keep functional all the systems that Tomas maintained here, but I will try to get familiar with the swig-wrapper code and start solving issues in 2018. Wish me luck.

**Comment by salvationFPS** [comment]
I forgot to close this issue. I found that this issue was on my side.
